when no payments are present skip filter and allow base error message to pop in instead of cryptic NoMethodError: undefined method 'first' for nil:NilClass